BaseURL = "https://elvissong.github.io/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "金窝银窝，不如狗窝"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true

[Author]
  Name = "coderzh"

[outputs]
  home = [ "RSS", "HTML" ]

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[Params]
  AuthorHomepage = "https://elvissong.github.com"
  BottomIntroduce = "一个半路出家的测试程序员 <br/> 想要做点想做的东西"
  Description = "Welcome to my blog! <br/> Hope you have fun here!"
  Subtitle = ""
  Weibo = "你看我头像是不是一条狗"
  WeiboID = 2557765741
  GitHub = "ElvisSong"
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

  [Params.GoogleAnalytics]
    ID = "UA-10147768-2"

  [Params.Gitment]
    ShortName = "elvis"

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 3
  [[Menu.Main]]
    Name = "生活"
    URL = "/life"
    Weight = 2